version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ot87qyuaqh7w"
s3_prefix = "todo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
